import type { EffectiveInterfaceLocale } from '../../app/i18n';

const EN_TITLES: Record<string, string> = {
  MD001: 'Heading levels should only increment by one level at a time',
  MD003: 'Heading style',
  MD004: 'Unordered list style',
  MD005: 'Inconsistent indentation for list items at the same level',
  MD007: 'Unordered list indentation',
  MD009: 'Trailing spaces',
  MD010: 'Hard tabs',
  MD011: 'Reversed link syntax',
  MD012: 'Multiple consecutive blank lines',
  MD013: 'Line length',
  MD014: 'Dollar signs used before commands without showing output',
  MD018: 'No space after hash on ATX-style heading',
  MD019: 'Multiple spaces after hash on ATX-style heading',
  MD020: 'No space inside hashes on closed ATX-style heading',
  MD021: 'Multiple spaces inside hashes on closed ATX-style heading',
  MD022: 'Headings should be surrounded by blank lines',
  MD023: 'Headings must start at the beginning of the line',
  MD024: 'Multiple headings with the same content',
  MD025: 'Multiple top-level headings in the same document',
  MD026: 'Trailing punctuation in heading',
  MD027: 'Multiple spaces after blockquote symbol',
  MD028: 'Blank line inside blockquote',
  MD029: 'Ordered list item prefix',
  MD030: 'Spaces after list markers',
  MD031: 'Fenced code blocks should be surrounded by blank lines',
  MD032: 'Lists should be surrounded by blank lines',
  MD033: 'Inline HTML',
  MD034: 'Bare URL used',
  MD035: 'Horizontal rule style',
  MD036: 'Emphasis used instead of a heading',
  MD037: 'Spaces inside emphasis markers',
  MD038: 'Spaces inside code span elements',
  MD039: 'Spaces inside link text',
  MD040: 'Fenced code blocks should have a language specified',
  MD041: 'First line in a file should be a top-level heading',
  MD042: 'No empty links',
  MD043: 'Required heading structure',
  MD044: 'Proper names should have the correct capitalization',
  MD045: 'Images should have alternate text',
  MD046: 'Code block style',
  MD047: 'Files should end with a single newline character',
  MD048: 'Code fence style',
  MD049: 'Emphasis style',
  MD050: 'Strong style',
  MD051: 'Link fragments should be valid',
  MD052: 'Reference links and images should use a defined label',
  MD053: 'Link and image reference definitions should be needed',
  MD054: 'Link and image style',
  MD055: 'Table pipe style',
  MD056: 'Table column count',
  MD058: 'Tables should be surrounded by blank lines',
  MD059: 'Link text should be descriptive',
  MD060: 'Table column style',
};

const ZH_CN_TITLES: Record<string, string> = {
  MD001: '标题层级每次只能递增一级',
  MD003: '标题样式',
  MD004: '无序列表样式',
  MD005: '同级列表项缩进不一致',
  MD007: '无序列表缩进',
  MD009: '行尾空格',
  MD010: '硬制表符',
  MD011: '链接语法顺序颠倒',
  MD012: '连续空行过多',
  MD013: '行长度',
  MD014: '命令前使用美元符号但未展示输出',
  MD018: 'ATX 标题井号后缺少空格',
  MD019: 'ATX 标题井号后有多个空格',
  MD020: '闭合 ATX 标题井号内侧缺少空格',
  MD021: '闭合 ATX 标题井号内侧有多个空格',
  MD022: '标题前后应有空行',
  MD023: '标题必须从行首开始',
  MD024: '多个标题内容相同',
  MD025: '文档中有多个一级标题',
  MD026: '标题末尾有标点',
  MD027: '引用符号后有多个空格',
  MD028: '引用块内有空行',
  MD029: '有序列表序号样式',
  MD030: '列表标记后的空格',
  MD031: '围栏代码块前后应有空行',
  MD032: '列表前后应有空行',
  MD033: '行内 HTML',
  MD034: '使用了裸 URL',
  MD035: '水平线样式',
  MD036: '使用强调代替标题',
  MD037: '强调标记内有空格',
  MD038: '行内代码标记内有空格',
  MD039: '链接文本内有空格',
  MD040: '围栏代码块应指定语言',
  MD041: '文件首行应为一级标题',
  MD042: '空链接',
  MD043: '标题结构不符合要求',
  MD044: '专有名称大小写不正确',
  MD045: '图片应有替代文本',
  MD046: '代码块样式',
  MD047: '文件末尾应只有一个换行符',
  MD048: '代码围栏样式',
  MD049: '强调样式',
  MD050: '加粗样式',
  MD051: '链接片段应有效',
  MD052: '引用链接和图片应使用已定义标签',
  MD053: '存在未使用的链接或图片引用定义',
  MD054: '链接和图片样式',
  MD055: '表格竖线样式',
  MD056: '表格列数',
  MD058: '表格前后应有空行',
  MD059: '链接文本应具有描述性',
  MD060: '表格列样式',
};

const ZH_TW_TITLES: Record<string, string> = {
  MD001: '標題層級每次只能遞增一級',
  MD003: '標題樣式',
  MD004: '無序清單樣式',
  MD005: '同級清單項目縮排不一致',
  MD007: '無序清單縮排',
  MD009: '行尾空格',
  MD010: '硬定位字元',
  MD011: '連結語法順序顛倒',
  MD012: '連續空行過多',
  MD013: '行長度',
  MD014: '命令前使用美元符號但未顯示輸出',
  MD018: 'ATX 標題井號後缺少空格',
  MD019: 'ATX 標題井號後有多個空格',
  MD020: '閉合 ATX 標題井號內側缺少空格',
  MD021: '閉合 ATX 標題井號內側有多個空格',
  MD022: '標題前後應有空行',
  MD023: '標題必須從行首開始',
  MD024: '多個標題內容相同',
  MD025: '文件中有多個一級標題',
  MD026: '標題末尾有標點',
  MD027: '引用符號後有多個空格',
  MD028: '引用區塊內有空行',
  MD029: '有序清單序號樣式',
  MD030: '清單標記後的空格',
  MD031: '圍欄程式碼區塊前後應有空行',
  MD032: '清單前後應有空行',
  MD033: '行內 HTML',
  MD034: '使用了裸 URL',
  MD035: '水平線樣式',
  MD036: '使用強調代替標題',
  MD037: '強調標記內有空格',
  MD038: '行內程式碼標記內有空格',
  MD039: '連結文字內有空格',
  MD040: '圍欄程式碼區塊應指定語言',
  MD041: '檔案首行應為一級標題',
  MD042: '空連結',
  MD043: '標題結構不符合要求',
  MD044: '專有名稱大小寫不正確',
  MD045: '圖片應有替代文字',
  MD046: '程式碼區塊樣式',
  MD047: '檔案末尾應只有一個換行字元',
  MD048: '程式碼圍欄樣式',
  MD049: '強調樣式',
  MD050: '粗體樣式',
  MD051: '連結片段應有效',
  MD052: '引用連結和圖片應使用已定義標籤',
  MD053: '存在未使用的連結或圖片引用定義',
  MD054: '連結和圖片樣式',
  MD055: '表格豎線樣式',
  MD056: '表格欄數',
  MD058: '表格前後應有空行',
  MD059: '連結文字應具有描述性',
  MD060: '表格欄樣式',
};

const JA_TITLES: Record<string, string> = {
  MD001: '見出しレベルは一度に 1 段階だけ上げる',
  MD003: '見出しのスタイル',
  MD004: '順序なしリストのスタイル',
  MD005: '同じ階層のリスト項目でインデントが不一致',
  MD007: '順序なしリストのインデント',
  MD009: '行末の空白',
  MD010: 'ハードタブ',
  MD011: 'リンク構文の順序が逆',
  MD012: '連続する空行が多すぎる',
  MD013: '行の長さ',
  MD014: '出力なしのコマンドにドル記号を使用',
  MD018: 'ATX 見出しの # の後に空白がない',
  MD019: 'ATX 見出しの # の後に複数の空白',
  MD020: '閉じた ATX 見出しの # の内側に空白がない',
  MD021: '閉じた ATX 見出しの # の内側に複数の空白',
  MD022: '見出しの前後に空行が必要',
  MD023: '見出しは行頭から開始する',
  MD024: '同じ内容の見出しが複数ある',
  MD025: '最上位の見出しが複数ある',
  MD026: '見出し末尾の句読点',
  MD027: '引用記号の後に複数の空白',
  MD028: '引用内の空行',
  MD029: '順序付きリスト項目の接頭辞',
  MD030: 'リスト記号の後の空白',
  MD031: 'フェンスコードの前後に空行が必要',
  MD032: 'リストの前後に空行が必要',
  MD033: 'インライン HTML',
  MD034: '裸の URL',
  MD035: '水平線のスタイル',
  MD036: '見出しの代わりに強調を使用',
  MD037: '強調記号内の空白',
  MD038: 'コードスパン内の空白',
  MD039: 'リンク文字列内の空白',
  MD040: 'フェンスコードに言語指定が必要',
  MD041: '先頭行は最上位見出しにする',
  MD042: '空のリンク',
  MD043: '必須の見出し構造',
  MD044: '固有名詞の大文字小文字',
  MD045: '画像に代替テキストが必要',
  MD046: 'コードブロックのスタイル',
  MD047: 'ファイル末尾は 1 つの改行にする',
  MD048: 'コードフェンスのスタイル',
  MD049: '強調のスタイル',
  MD050: '強調表示のスタイル',
  MD051: 'リンクフラグメントは有効にする',
  MD052: '参照リンクと画像は定義済みラベルを使用する',
  MD053: '不要な参照定義',
  MD054: 'リンクと画像のスタイル',
  MD055: '表のパイプスタイル',
  MD056: '表の列数',
  MD058: '表の前後に空行が必要',
  MD059: 'リンク文字列は説明的にする',
  MD060: '表の列スタイル',
};

const TITLES: Record<EffectiveInterfaceLocale, Record<string, string>> = {
  'zh-CN': ZH_CN_TITLES,
  'zh-TW': ZH_TW_TITLES,
  'en-US': EN_TITLES,
  'ja-JP': JA_TITLES,
};

export function getMarkdownLintRuleTitle(
  ruleId: string,
  fallback: string,
  locale: EffectiveInterfaceLocale,
): string {
  return TITLES[locale][ruleId] ?? fallback;
}
